version: "3.9"

services:
  web:
    build: .
    image: glowin-web:latest
    container_name: glowin_web
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/app:ro
