name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: GlowIn
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint import
        run: |
          python -c "import sys; sys.path.append('GlowIn'); import app; print('App import OK')"

      - name: Build Docker image
        working-directory: GlowIn
        run: |
          docker build -t glowin-web:ci .


